spring.application.name=CarRentalEurekaServer
server.port=6660

# Fix for the Config Server Error
spring.cloud.config.enabled=false

# Eureka server configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.wait-time-in-ms-when-sync-empty=0
eureka.client.service-url.defaultZone=http://localhost:6660/eureka/

# If you kept JPA/MySQL in POM, you MUST provide DB details or tests will fail
# spring.datasource.url=jdbc:mysql://localhost:3306/eureka_db
# spring.datasource.username=root
# spring.datasource.password=root
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver